Repository edwindelbosque/picasso-fe, pull requests merged in 2019-12, with the labels that each got.

#1 Set up boiler-plates and install necessary npm packages
  package-lock.json
  package.json
  public/favicon.ico
  public/favicon.png
  public/index.html
  src/App.js
  src/App.test.js
  src/components/App/App.js
  src/components/App/App.scss
  src/components/App/App.test.js
  src/components/App/__snapshots__/App.test.js.snap
  src/index.js
  src/index.scss
  src/logo.svg
  src/serviceWorker.js
  src/setupTests.js
Labels: documentation

#2 Add new Favicon and make App component a class component
  public/favicon.png
  src/components/App/App.js
  src/components/App/App.scss
Labels: documentation, enhancement

#3 Edb boilerplates and packages
  package-lock.json
  package.json
  public/index.html
  src/components/App/App.js
  src/components/App/App.scss
  src/components/App/__snapshots__/App.test.js.snap
  src/index.scss
Labels: documentation

#4 Edb travis ci installation
  .travis.yml
  package.json
Labels: documentation

#7 Add apiCalls for GET and POST
  src/actions/index.js
  src/reducers/index.js
  src/util/apiCalls.js
  src/util/apiCleaners.js
Labels: enhancement, testing

#8 Mm random color fetch
  package-lock.json
  package.json
  src/App.js
  src/apiCalls.js/apiCalls.js
  src/apiCalls.js/apiCalls.test.js
  src/components/LoginForm/loginForm.js
  src/containersmm/loginForm/login.js
  src/setupTests.js
Labels: enhancement, testing

#9 Mm login form
  package-lock.json
  package.json
  src/App.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/LoginForm/loginForm.js
  src/util/apiCalls.js
Labels: enhancement

#10 Edb nav bar
  package-lock.json
  package.json
  src/actions/index.js
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Catalogs/Catalogs.js
  src/components/Catalogs/Catalogs.scss
  src/components/Catalogs/Catalogs.test.js
  src/components/Catalogs/__snapshots__/Catalogs.test.js.snap
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/Footer.test.js
  src/components/Footer/__snapshots__/Footer.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/NavBar/__snapshots__/NavBar.test.js.snap
  src/components/PaletteCard/PaletteCard.js
  src/components/PaletteCard/PaletteCard.scss
  src/components/PaletteCard/PaletteCard.test.js
  src/components/PaletteCard/__snapshots__/PaletteCard.test.js.snap
  src/components/Palettes/Palettes.js
  src/components/Palettes/Palettes.scss
  src/components/Palettes/Palettes.test.js
  src/components/Palettes/__snapshots__/Palettes.test.js.snap
  src/index.js
  src/reducers/index.js
Labels: enhancement, testing

#11 Add create account functionality with successful and unsuccessful res…
  src/components/App/App.js
  src/components/LoginForm/loginForm.js
  src/components/UserSignupForm/UserSignupForm.js
  src/util/apiCalls.js
Labels: enhancement

#12 Mm random colors
  src/components/App/App.js
  src/components/RandomColor/RandomColor.js
  src/util/apiCalls.js
  src/util/cleanerFunctions.js
Labels: enhancement

#14 Mm random colors
  src/App.js
  src/components/App/App.js
  src/components/LoginForm/loginForm.js
  src/components/RandomColor/RandomColor.js
  src/components/RandomColor/RandomColor.scss
  src/components/RandomPalette/RandomPalette.js
  src/components/RandomPalette/RandomPalette.scss
  src/util/apiCalls.js
  src/util/cleanerFunctions.js
Labels: enhancement

#17 POST (add) new palette
  src/components/RandomColor/RandomColor.js
  src/util/apiCalls.js
Labels: enhancement

#18 Improve main palette generator styling
  src/components/RandomColor/RandomColor.scss
  src/components/RandomPalette/RandomPalette.js
  src/components/RandomPalette/RandomPalette.scss
Labels: enhancement

#19 Edb palette generator
  src/assets/logoutIcon.png
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/NavBar/__snapshots__/NavBar.test.js.snap
  src/components/RandomColor/RandomColor.js
  src/components/RandomColor/RandomColor.scss
  src/components/RandomPalette/RandomPalette.js
  src/components/RandomPalette/RandomPalette.scss
  src/components/SaveMenu/SaveMenu.js
  src/components/SaveMenu/SaveMenu.scss
Labels: enhancement

#20 Mm fetch palettes
  src/components/App/App.js
  src/components/LoginForm/LoginForm.js
  src/components/NavBar/NavBar.js
  src/components/PaletteCard/PaletteCard.js
Labels: bug

#21 Edb palette generator
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/PaletteCard/PaletteCard.js
  src/components/PaletteCard/PaletteCard.scss
  src/components/PaletteCard/PaletteCard.test.js
  src/components/PaletteCard/__snapshots__/PaletteCard.test.js.snap
  src/components/Palettes/Palettes.js
  src/components/RandomColor/RandomColor.js
  src/components/SaveMenu/SaveMenu.js
  src/util/apiCalls.js
Labels: bug, enhancement, testing

#22 Edb palette generator
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/NavBar/__snapshots__/NavBar.test.js.snap
  src/components/PaletteCard/PaletteCard.scss
Labels: enhancement

#25 Create/POST new catalogs with new palette
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Catalogs/Catalogs.js
  src/components/LoginForm/LoginForm.js
  src/components/RandomColor/RandomColor.js
  src/components/SaveMenu/SaveMenu.js
  src/util/apiCalls.js
Labels: bug, enhancement, testing

#37 Creates two Catalogs and Palettes when new user is created
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Catalogs/Catalogs.js
  src/components/LoginForm/LoginForm.js
  src/components/NavBar/NavBar.js
  src/components/SaveMenu/SaveMenu.js
  src/components/UserSignupForm/UserSignupForm.js
  src/util/apiCalls.js
  src/util/userCreatorFunctions.js
Labels: bug, enhancement

#38 Fix bugs, clean code, replace App class for hooks, lint
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Catalogs/Catalogs.js
  src/components/Catalogs/Catalogs.scss
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/__snapshots__/LoginForm.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/NavBar/__snapshots__/NavBar.test.js.snap
  src/components/PaletteCard/PaletteCard.js
  src/components/PaletteCard/PaletteCard.scss
  src/components/PaletteCard/PaletteCard.test.js
  src/components/PaletteCard/__snapshots__/PaletteCard.test.js.snap
  src/components/Palettes/Palettes.js
  src/components/Palettes/Palettes.scss
  src/components/Palettes/__snapshots__/Palettes.test.js.snap
  src/components/RandomColor/RandomColor.js
  src/components/SaveMenu/SaveMenu.js
  src/components/SaveMenu/SaveMenu.scss
  src/components/UserSignupForm/UserSignupForm.js
  src/util/apiCalls.js
  src/util/userCreatorFunctions.js
Labels: bug, enhancement

#40 Refactor newUserCatalogAndPalettes.js and Catalogs.js files
  src/components/Catalogs/Catalogs.js
  src/components/Catalogs/__snapshots__/Catalogs.test.js.snap
  src/util/userCreatorFunctions.js
Labels: bug

#41 Add feature to delete catalogs and fix signup
  src/apiCalls.js/apiCalls.js
  src/apiCalls.js/apiCalls.test.js
  src/components/App/App.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Catalogs/Catalogs.js
  src/components/Catalogs/Catalogs.scss
  src/components/Catalogs/__snapshots__/Catalogs.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/PaletteCard/PaletteCard.js
  src/components/RandomColor/RandomColor.js
  src/components/SaveMenu/SaveMenu.js
  src/components/UserSignupForm/UserSignupForm.js
  src/util/apiCalls.js
  src/util/apiCleaners.js
  src/util/cleanerFunctions.js
  src/util/userCreatorFunctions.js
Labels: bug, enhancement, testing
